# Generated by Django 2.0.7 on 2018-07-20 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_loc', models.CharField(max_length=50)),
                ('end_loc', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 20, 17, 39, 42, 665517, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
